### PR TITLE
ENH: Various improvements

### PR DESCRIPTION
**Pull request by candleindark**
This PR improves the existing conversion from Pydantic models to LinkML the following areas:

1. Improve enum conversion so that different slots within the `EnumDefinition` metamodel are populated more accurately
2. Add more detailed slots population
3. Add `slot usage` in class population
4. Provide a more accurate interpretation of slots/attributes in a class, by eliminating misinterpretation of a class variable in a Pydantic model as a slot for example.
5. Add checks for unmet assumptions about the given schema implemented with Pydantic
6. Specify limitations of this conversion tool in `README.md`
7. Provide more tests to improve coverage
8. Reorganized code so that additional support can be added more easily
9. Provide a solution in handling a Pydantic model that has multiple parents that are also Pydantic models.
10. Organize this repo into a Python project using Hatch
11. Enable CLI to be installed as part of the project installation.

TODOs to achieve the above implementation.

- [x] Lay out a `LinkmlGenerator` class that takes in Python `Enum` objects and Pydantic models for conversion to LinkML schema
- [x] Resolve Pydantic core schema for each model and each field
- [x] Identify locally defined fields for each model, e.g. filter out those in `__annotations__` that are `ClassVar`
- [x] Separate locally defined fields as newly defined ones and overriding ones. The newly defined ones are to be used for global slot definitions, and the overriding ones are to be used for slot usage definitions.
- [x] Layout a `SlotGenerator` class for generating slot definition from the Pydantic core schema for a field in a Pydantic model
- [ ] Implement conversion of elemental Pydantic core schema to LinkML slot attribute values in `SlotGenerator`
    - [ ] Some special care possibly needed to be put in place for conversion of numeric types because "`exclusiveMaximum`" and "`exclusiveMinimum`" are [currently not available](https://github.com/orgs/linkml/discussions/2144) in LinkML
- [ ] Implement the conversion of Pydantic core model schemas for Pydantic models to LinkML class definitions.

Requests filed in pursue of completing this PR.
1. LinkML

    1. Questions needed to be answered: 

    - [ ]     1. [How to specify a slot of range float that accepts values less than 10.0? #2144](https://github.com/orgs/linkml/discussions/2144)
                 (May not be needed for dandischema but needed for the support of other schemas)
    - [x]     2. [What are the default values for meta model slots? #2147](https://github.com/orgs/linkml/discussions/2147)
                 (Needed for dandischema but the question is mostly answered) 
    - [ ]     3. [Is there a way to specify a default value for a slot with a range of an arbitrary type? #2149](https://github.com/orgs/linkml/discussions/2149)
                 (May not be needed for dandischema but needed for the support of other schemas)
    - [ ]     4. [How to specify the LinkML equivalent of Union[List[int], str]? #2154](https://github.com/orgs/linkml/discussions/2154)
                (Needed for Dandischema which has field types such as `Optional[Union[List[GenotypeInfo], Identifier]]`)
       - [ ]  1. https://github.com/linkml/linkml/issues/2190 
    - [ ]     5. [How to define a slot whose values are comparable to a dictionary in Python?](https://github.com/orgs/linkml/discussions/2239)
               (Needed for Dandischema which has field type of `Dict[DigestType, str]` for `digest` in `BareAsset`.)
   
    2. Issues
        1. https://github.com/linkml/linkml/issues/2138
            (Needed for dandischema which has enum values containing `":"`.)
        2. https://github.com/linkml/linkml/issues/2104
           (Not needed. There is a workaround.)
        3. https://github.com/linkml/linkml/issues/2155
            (Solution not needed for our purpose)
        4. https://github.com/linkml/linkml/issues/2206
            (Not needed. Found a workaround)
        5. https://github.com/linkml/linkml/issues/2215
            (Needed for the current translation of URL types in Pydantic)
        6. https://github.com/linkml/linkml/issues/1508#issuecomment-2292431671
            (Needed for all translations)

8. Pydantic
    1. https://github.com/pydantic/pydantic/discussions/9485 

***Note:***
This PR has been migrated and merged by https://github.com/dandi/pydantic2linkml/pull/1.

The remaining issues and steps are to be tracked with https://github.com/dandi/pydantic2linkml/issues/2

### CODE REVIEW

**Comment by candleindark** [comment]
@satra @djarecka @yarikoptic The assumption that there is exactly one Pydantic model corresponds to a class in a target LinkML schema is incorrect in `aind_data_schema`.

This conversion tool to LinkML schema is able to pickup name collisions in classes and enums. Here is the error.

```
>           raise NameCollisionError(err_msg)
E           pydantic2linkml.exceptions.NameCollisionError: Name collision @ Isi: [<class 'aind_data_schema.models.platforms.Isi'>, <class 'aind_data_schema.models.modalities.Isi'>]; Name collision @ Confocal: [<class 'aind_data_schema.models.platforms.Confocal'>, <class 'aind_data_schema.models.modalities.Confocal'>]; Name collision @ Merfish: [<class 'aind_data_schema.models.modalities.Merfish'>, <class 'aind_data_schema.models.platforms.Merfish'>]; Name collision @ Behavior: [<class 'aind_data_schema.models.modalities.Behavior'>, <class 'aind_data_schema.models.platforms.Behavior'>, <class 'aind_data_schema.models.harp_types.Behavior'>]; Name collision @ Olfactometer: [<class 'aind_data_schema.models.harp_types.Olfactometer'>, <class 'aind_data_schema.models.devices.Olfactometer'>]; Name collision @ Ecephys: [<class 'aind_data_schema.models.platforms.Ecephys'>, <class 'aind_data_schema.models.modalities.Ecephys'>]; Name collision @ Mri: [<class 'aind_data_schema.models.platforms.Mri'>, <class 'aind_data_schema.models.modalities.Mri'>]
```

As you can see, class names such as `Isi` and `Confocal` are used multiples times across different modules. I checked the `Isi` and `Confocal` classes, classes with the same name are very very similar. Any idea on how to handle these name conflicts?

P.S. We don't have this problem on dandischema.

**Comment by satra** [comment]
@saskiad - any thoughts on the above comment would be much appreciated. this is the pydantic to linkml conversion effort and issac is writing a converter that hopefully generalizes to multiple models.

@candleindark -  as a first pass we could augment class name with module name to create a unique class. this would require storing that info. the second thing is to check what's different between the classes.

**Comment by saskiad** [comment]
The problem here is two different enumerated lists that use the same names? We want to avoid name collisions in the schema classes, but these are in the controlled vocabularies. I'm not entirely sure we can avoid that, but let me think about it some.

**Comment by candleindark** [comment]
> The problem here is two different enumerated lists that use the same names? We want to avoid name collisions in the schema classes, but these are in the controlled vocabularies. I'm not entirely sure we can avoid that, but let me think about it some.

The problem is that multiple classes defined in different modules share the same name. For example, `<class 'aind_data_schema.models.platforms.Behavior'>` and `<class 'aind_data_schema.models.harp_types.Behavior'>` share the name `Behavior`. In a LinkML schema, all classes need to have a unique name. In fact, from my own experimentation with LinkML, a class can't have the same name as an enum either.

**Comment by saskiad** [comment]
So we should start with you updating the schema version. These were all moved to a separate repo a bit ago. aind-data-schema-models. We still use them this way - to enumerate our platforms and modalities and harp devices. But I wonder if it's going to give you the same problem when they are coming from outside the schema?

**Comment by candleindark** [comment]
> So we should start with you updating the schema version. These were all moved to a separate repo a bit ago. aind-data-schema-models. We still use them this way - to enumerate our platforms and modalities and harp devices. But I wonder if it's going to give you the same problem when they are coming from outside the schema?

Updating `aind-data-schema` to 0.38.0, the latest, solved the problem. Thanks. 

However, this version of `aind-data-schema` [pins Pydantic to under 2.7](https://github.com/AllenNeuralDynamics/aind-data-schema/commit/2461ea38a4145c1a15e119c56eb9ca28946952a8). Will you remove that restriction any time soon? This conversion tool may not work well with Pydantic 2.7 (some tests failed). With the currently version of Pydantic, I was able to get all tests passed though.

**Comment by saskiad** [comment]
Current version of Pydantic breaks things - I forget what. We're working on it, but I don't expect to unpin it soon.

**Comment by candleindark** [comment]
@saskiad @satra After taking a closer look, I noticed that a `aind_data_schema`, at version 0.38.0, no longer have a central "root module" (it used to be `aind_data_schema.models` from which all models definition can be located through recursive imports. Most of the models seem to be defined in the following files, and the supporting package `aind-data-schema-models`.

```python
            "aind_data_schema.components.coordinates",
            "aind_data_schema.components.devices",
            "aind_data_schema.components.reagent",
            "aind_data_schema.components.stimulus",
            "aind_data_schema.components.tile",
            "aind_data_schema.core.acquisition",
            "aind_data_schema.core.data_description",
            "aind_data_schema.core.instrument",
            "aind_data_schema.core.metadata",
            "aind_data_schema.core.procedures",
            "aind_data_schema.core.processing",
            "aind_data_schema.core.rig",
            "aind_data_schema.core.session",
            "aind_data_schema.core.subject",
```

They are well organized, but in parallel, so we can't retrieve all the models in the project through one root module alone. Many of the name collisions were eliminated in running this LinkML conversion tool with these modules as input individually, but it was only due to the separation of the use of models instead of elimination reuse of the same class name. For example, when using `aind_data_schema.components.devices` as the root module for this tool, there was still the following name collection at `"Olfactometer"` as a class name.

```
E           pydantic2linkml.exceptions.NameCollisionError: Name collision @ Olfactometer: [<class 'aind_data_schema.components.devices.Olfactometer'>, <class 'aind_data_schema_models.harp_types.Olfactometer'>]
```

We can support loading of multiple root modules to locate the models in the project, but the name collision problem remains for converting the `aind_data_schema` to LinkML schema (we can take @satra  [approach](https://github.com/DailyDreaming/linkml-aind-model/pull/13#issuecomment-2145059575) to solve this though).

**Comment by satra** [comment]
@DailyDreaming - can we transfer this repo to dandi org? if you give me admin access on this repo i can take care of it.

**Comment by candleindark** [comment]
This PR has been migrated and merged by https://github.com/dandi/pydantic2linkml/pull/1.

The remaining issues and steps are to be tracked with https://github.com/dandi/pydantic2linkml/issues/2

@yarikoptic Should I just close this PR at this point?

**Pull request closed without merging**
